CREATE TABLE IF NOT EXISTS views(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128),
    query VARCHAR(2048)
);
CREATE TABLE IF NOT EXISTS forms(
    id INT AUTO_INCREMENT PRIMARY KEY,
    column_names VARCHAR(2048),
    column_types VARCHAR(2048)
);